FROM scorpil/rust:nightly

RUN apt-get update && apt-get install -y libssl-dev pkg-config libssh-dev cmake

COPY ./Cargo.lock ./Cargo.toml ./LICENSE /rust/app/
COPY ./src /rust/app/src

WORKDIR /rust/app
VOLUME /rust/app/target

CMD cargo build --release
